# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [86]:
## SELIMHAN MERAL

import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [85]:
## These are common functions so i don't write comment on them

np.arange(6)

array([0, 1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [84]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [7]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [83]:
# Created array like wanted after print values from numpy array
a = np.arange(10,70,5)
#with for 
for i in a:
    print(i)

10
15
20
25
30
35
40
45
50
55
60
65


6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [23]:
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [24]:
np.random.randn(3,5)

array([[ 1.35198236, -0.25937897, -0.38987485,  0.33491451, -2.40996707],
       [ 1.56972246,  2.19486894,  0.64823179,  1.39780851, -0.84934493],
       [-0.52388769, -1.71348985,  0.60443348, -0.44457435,  1.61255351]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [29]:
np.arange(0,24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [38]:
# random.random function create values between 0 and 1
a = np.random.random(10)
print('min value :{}\nmax value :{}'.format((min(a)),max(a)))

min value :0.012799329966620365
max value :0.7204952514090919


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [49]:
# there is more way to solve this problem
np.random.randn(6,6)
arr = np.random.random(36).reshape(6,6)
arr

array([[0.96688132, 0.89038533, 0.72004709, 0.58705772, 0.61483921,
        0.77320377],
       [0.54962598, 0.83500764, 0.02864489, 0.68079814, 0.29747566,
        0.99560071],
       [0.56913586, 0.86642712, 0.20115614, 0.31617136, 0.15398618,
        0.64001176],
       [0.2766198 , 0.79154369, 0.1319644 , 0.384319  , 0.46717502,
        0.99709421],
       [0.09538156, 0.45438443, 0.26777258, 0.48130238, 0.38110202,
        0.72152749],
       [0.38262802, 0.42140297, 0.81733932, 0.36519483, 0.4773444 ,
        0.42718275]])

12- 5.satırdaki elemanları gösteriniz.

In [56]:
arr[4]

array([0.09538156, 0.45438443, 0.26777258, 0.48130238, 0.38110202,
       0.72152749])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [63]:
arr[5,5]

0.42718274832657355

14-4.sutundaki tüm elemanları çekin.

In [58]:
new = arr[3]
new

array([0.2766198 , 0.79154369, 0.1319644 , 0.384319  , 0.46717502,
       0.99709421])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [64]:
for i in new.flat:
    print(i)

0.27661980479033943
0.7915436924170852
0.13196440293002654
0.38431899569929207
0.4671750249672002
0.9970942068964491


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [70]:
a = np.random.random(5)*5
print(a)


[3.53498521 4.04051673 3.15577412 4.39760039 4.43900162]


16- Satırların toplam değeri nedir?

In [71]:
a.sum()

19.567878072477562

17-Satırların standart sapma değeri nedir?

In [72]:
a.std()

0.4988106476417781

18-Satırların varyans değeri nedir?

In [73]:
a.var()

0.24881206220081015

19- Satırların transpoz değeri nedir?

In [80]:
# a.T does not give expected result
np.array([a]).T

array([[3.53498521],
       [4.04051673],
       [3.15577412],
       [4.39760039],
       [4.43900162]])